name: Build_ax3600

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
#  schedule:
#    - cron: 30 3 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Build_ax3600:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

        
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/Tony91590/qsdk-5.4
        REPO_BRANCH: Test-ci
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        cp -f ../diy-part1.sh ./
        chmod +x ./diy-part1.sh && ./diy-part1.sh
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp -f ../diy-part2.sh ./        
        chmod +x ./diy-part2.sh && ./diy-part2.sh
 
    - name: Configuration Customization - Build_ax3600
      env:
        CONFIG_FILE: './.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        make -j$(nproc) V=s

    - name: Assemble Artifact
      id: assemble_artifact
      run: |
        rm -rf ./AX3600_Out
        mkdir -p ./AX3600_Out/
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-sysupgrade.bin ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-sysupgrade.bin
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-factory.ubi ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-factory.ubi
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600-initramfs-fit-uImage.itb ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600-initramfs-fit-uImage.itb
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600.manifest ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600.manifest
        cp -a openwrt/bin/targets/ipq807x/generic/config.buildinfo ./AX3600_Out/config.buildinfo
        cp -a openwrt/bin/targets/ipq807x/generic/feeds.buildinfo ./AX3600_Out/feeds.buildinfo
        cp -a openwrt/bin/targets/ipq807x/generic/version.buildinfo ./AX3600_Out/version.buildinfo
        cp -a openwrt/bin/targets/ipq807x/generic/sha256sums ./AX3600_Out/sha256sums
        
    - name: Upload Firmwares
      uses: actions/upload-artifact@main
      with:
        name: AX3600-OpenWrt
        path: AX3600_Out/* 
        
    - name: Generate Tag & Release Name
      id: generate_name
      run: |
        time=$(date +%Y%m%d%H%M)
        release_tag="$time"
        release_name="Xiaomi-AX3600-OpenWrt-5.10-$(date +%Y%m%d)"
        echo "##[set-output name=release_name;]$release_name"
        echo "##[set-output name=release_tag;]$release_tag"        
    - name: Create Release & Upload
      uses: ncipollo/release-action@v1
      with:
        artifacts: AX3600_Out/*
        name: ${{ steps.generate_name.outputs.release_name }}
        tag: ${{ steps.generate_name.outputs.release_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}           
