name: Build_ax3600

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
#  schedule:
#    - cron: 30 3 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Build_ax3600:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/Tony91590/R3600
        REPO_BRANCH: test
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        cp config-ax3600-512M .config
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
          make package/symlinks
 
    - name: Download deconf
      working-directory: ./openwrt
      run: |
          make defconfig 
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        make -j$(nproc) V=s

    - name: Assemble Artifact
      id: assemble_artifact
      run: |
        rm -rf ./AX3600_Out
        mkdir -p ./AX3600_Out/
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-sysupgrade.bin ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-sysupgrade.bin
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-factory.bin ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-factory.bin
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600-initramfs-fit-uImage.itb ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600-initramfs-fit-uImage.itb
        cp -a openwrt/bin/targets/ipq807x/generic/openwrt-ipq807x-generic-xiaomi_ax3600.manifest ./AX3600_Out/openwrt-ipq807x-generic-xiaomi_ax3600.manifest
        cp -a openwrt/bin/targets/ipq807x/generic/config.buildinfo ./AX3600_Out/config.buildinfo
        cp -a openwrt/bin/targets/ipq807x/generic/feeds.buildinfo ./AX3600_Out/feeds.buildinfo
        cp -a openwrt/bin/targets/ipq807x/generic/profiles.json ./AX3600_Out/profiles.json
        cp -a openwrt/bin/targets/ipq807x/generic/version.buildinfo ./AX3600_Out/version.buildinfo
        cp -a openwrt/bin/targets/ipq807x/generic/sha256sums ./AX3600_Out/sha256sums
        
    - name: Upload Firmwares
      uses: actions/upload-artifact@main
      with:
        name: AX3600-OpenWrt
        path: AX3600_Out/* 
        
    - name: Generate Tag & Release Name
      id: generate_name
      run: |
        time=$(date +%Y%m%d%H%M)
        release_tag="$time"
        release_name="Xiaomi-AX3600-OpenWrt-5.10-$(date +%Y%m%d)"
        echo "##[set-output name=release_name;]$release_name"
        echo "##[set-output name=release_tag;]$release_tag"        
    - name: Create Release & Upload
      uses: ncipollo/release-action@v1
      with:
        artifacts: AX3600_Out/*
        name: ${{ steps.generate_name.outputs.release_name }}
        tag: ${{ steps.generate_name.outputs.release_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}           
